/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".example-container[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    flex-direction: column;\r\n    position: absolute;\r\n    top: 0;\r\n    bottom: 0;\r\n    left: 0;\r\n    right: 0;\r\n  }\r\n  \r\n  .example-is-mobile[_ngcontent-%COMP%]   .example-toolbar[_ngcontent-%COMP%] {\r\n    position: fixed;\r\n    \r\n    z-index: 2;\r\n  }\r\n  \r\n  h1.example-app-name[_ngcontent-%COMP%] {\r\n    margin-left: 8px;\r\n  }\r\n  \r\n  .example-sidenav-container[_ngcontent-%COMP%] {\r\n    \r\n    flex: 1;\r\n  }\r\n  \r\n  .example-is-mobile[_ngcontent-%COMP%]   .example-sidenav-container[_ngcontent-%COMP%] {\r\n    \r\n    flex: 1 0 auto;\r\n  }"];
export { styles as styles };
//# sourceMappingURL=pxt-app-header.component.css.shim.ngstyle.js.map